[workspace]
members = ["lib/comic2pdf", "bin/fileconv"]
resolver = "3"

# Shared dependencies across all crates (optional, minimizes version drift)
[workspace.dependencies]
unrar = "0.5.8"
krilla = "0.8.2"
#printpdf = "0.7"
#pdf-writer = "0.12"
#rayon = "1.10"    # For blazing fast parallel image embedding
#natord = "1.0"     # Critically important for sorting pages correctly (1, 2, ... 10)
#tempfile = "3.10"  # To cleanly extract pages to disk without bloating RAM
#clap = { version = "4.5", features = ["derive", "env"] }
